workflows:
  ios-workflow:
    name: iOS Build
    
    # [NEW] Link the API Key from Codemagic UI
    # Replace "My App Store Key" with the exact reference name you saved in Team Settings > Integrations.
    integrations:
      app_store_connect: My App Store Key

    environment:
      xcode: latest
      node: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
          
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # [FIX] Remove existing ios folder to force a clean generation
          rm -rf ios
          
          # Add platform and sync
          npx cap add ios
          npx cap sync
          
          # [FIX] Install Pods to generate the missing App.xcworkspace
          cd ios/App
          pod install

      - name: iOS Code Signing
        script: |
          keychain initialize
          
          # [UPDATE] This now uses the API key linked in the 'integrations' section above
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" \
            --type IOS_APP_STORE \
            --create
            
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # Verify workspace exists
          if [ ! -d "App.xcworkspace" ]; then
            echo "Error: App.xcworkspace not found! Pod install likely failed."
            exit 1
          fi

          # Archive using the workspace
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportOptionsPlist ../../export_options.plist \
            -exportPath .
          
          mv App.ipa app_signed.ipa

    artifacts:
      - ios/App/*.ipa

    publishing:
      # [UPDATE] Uses the 'integration' auth method instead of manual variables
      app_store_connect:
        auth: integration
        submit_to_testflight: true