workflows:
  ios-workflow:
    name: iOS Build
    
    # Link the API Key from Codemagic UI
    integrations:
      app_store_connect: Personal

    environment:
      xcode: latest
      node: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
          
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # Remove existing ios folder to force a clean generation
          rm -rf ios
          
          # Add platform and sync
          npx cap add ios
          npx cap sync
          
          # [FIXED] Only run pod install if a Podfile was actually generated
          cd ios/App
          if [ -f "Podfile" ]; then
            echo "Podfile found. Installing Pods..."
            pod install
          else
            echo "No Podfile found. Skipping CocoaPods (using SPM)."
          fi

      - name: iOS Code Signing
        script: |
          keychain initialize
          
          # Fetch certificates
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" \
            --type IOS_APP_STORE \
            --create
            
          keychain add-certificates
          
          # [FIXED] Apply profiles to the Project (works for both Pods and SPM)
          xcode-project use-profiles

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # [FIXED] Smart Logic: Detect if we should build a Workspace (Pods) or Project (SPM)
          if [ -d "App.xcworkspace" ]; then
            echo "Building Workspace..."
            BUILD_ARG="-workspace App.xcworkspace"
          else
            echo "Building Project (SPM)..."
            BUILD_ARG="-project App.xcodeproj"
          fi

          # Archive
          xcodebuild archive \
            $BUILD_ARG \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportOptionsPlist ../../export_options.plist \
            -exportPath .
          
          mv App.ipa app_signed.ipa

    artifacts:
      - ios/App/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true