workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install Dependencies
        script: |
          # Force clean install to avoid Windows/Mac permission issues
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # Create the iOS project folder
          npx cap add ios
          npx cap sync
      
      - name: Build IPA (Unsigned)
        script: |
          # [FIX 1] Go into the correct 'App' folder where the workspace lives
          cd ios/App
          
          # [FIX 2] Archive the build with Signing disabled
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
          
          # [FIX 3] Manually package the IPA (Bypasses the missing .plist error)
          mkdir Payload
          cp -r App.xcarchive/Products/Applications/App.app Payload/
          zip -r App.ipa Payload
          
    artifacts:
      - ios/App/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true