workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          npx cap add ios
          npx cap sync

      # [NEW STEP] Fetch Certificates and Profiles from Apple
      # This requires APP_STORE_CONNECT_PRIVATE_KEY, KEY_IDENTIFIER, and ISSUER_ID 
      # to be set in Environment Variables.
      - name: iOS Code Signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # [FIXED] Use standard archive command allowing signing
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates
          
          # Export the IPA using the archive
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportOptionsPlist ../../export_options.plist \
            -exportPath .
          
          # Rename for consistency if needed, though export usually names it App.ipa
          mv App.ipa app_signed.ipa

    artifacts:
      - ios/App/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true