workflows:
  ios-workflow:
    name: iOS Build
    
    integrations:
      app_store_connect: Personal

    environment:
      xcode: latest
      node: latest
      cocoapods: default
      # [NEW] Automatic Code Signing Configuration
      # Documentation: Fetching files by distribution type and bundle identifier
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.your.bundle.id # <--- UPDATE THIS with your actual Bundle ID
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
          
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # Clean restart of ios folder
          rm -rf ios
          npx cap add ios
          npx cap sync
          
          # Check for Podfile to decide on Pods vs SPM
          cd ios/App
          if [ -f "Podfile" ]; then
            echo "Podfile found. Installing Pods..."
            pod install
          else
            echo "No Podfile found. Skipping CocoaPods (using SPM)."
          fi

      - name: iOS Code Signing
        script: |
          # Change context to the iOS App directory
          cd ios/App
          
          # [NEW] Apply the profiles fetched by the 'ios_signing' environment configuration.
          # As per docs: "Steps Initialize keychain & Add certificates... are not required"
          xcode-project use-profiles

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # Detect Workspace (Pods) vs Project (SPM)
          if [ -d "App.xcworkspace" ]; then
            echo "Building Workspace..."
            BUILD_ARG="-workspace App.xcworkspace"
          else
            echo "Building Project (SPM)..."
            BUILD_ARG="-project App.xcodeproj"
          fi

          # Build Archive
          # Note: We no longer pass DEVELOPMENT_TEAM explicitly.
          # 'xcode-project use-profiles' has already updated the project settings with the correct Team ID.
          xcodebuild archive \
            $BUILD_ARG \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE="Manual"
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportOptionsPlist ../../export_options.plist \
            -exportPath .
          
          mv App.ipa app_signed.ipa

    artifacts:
      - ios/App/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true