workflows:
  ios-workflow:
    name: iOS Build
    
    integrations:
      app_store_connect: Personal

    environment:
      xcode: latest
      node: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
          
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # Clean restart of ios folder
          rm -rf ios
          npx cap add ios
          npx cap sync
          
          # Check for Podfile to decide on Pods vs SPM
          cd ios/App
          if [ -f "Podfile" ]; then
            echo "Podfile found. Installing Pods..."
            pod install
          else
            echo "No Podfile found. Skipping CocoaPods (using SPM)."
          fi

      - name: iOS Code Signing
        script: |
          # Change context to the iOS App directory so xcode-project commands work
          cd ios/App
          
          keychain initialize
          
          # 1. Fetch Signing Files using the detected Bundle ID from the correct path
          APP_ID=$(xcode-project detect-bundle-id)
          echo "Detected Bundle ID: $APP_ID"
          
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create
            
          keychain add-certificates
          xcode-project use-profiles

          # 2. Extract Team ID from the fetched profile
          # We look for the first mobileprovision file downloaded by the previous step
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          
          if [ -z "$PROFILE_PATH" ]; then
            echo "Error: No provisioning profile found!"
            exit 1
          fi
          
          echo "Found Profile: $PROFILE_PATH"

          # Extract the TeamIdentifier using standard macOS tools
          TEAM_ID=$(security cms -D -i "$PROFILE_PATH" | /usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" /dev/stdin)
          
          if [ -z "$TEAM_ID" ]; then
             echo "Error: Could not extract Team ID from profile."
             exit 1
          fi

          echo "Detected Development Team ID: $TEAM_ID"
          
          # Export it to the Codemagic environment so the next step can use it
          echo "DEVELOPMENT_TEAM=$TEAM_ID" >> $CM_ENV

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # Detect Workspace (Pods) vs Project (SPM)
          if [ -d "App.xcworkspace" ]; then
            echo "Building Workspace..."
            BUILD_ARG="-workspace App.xcworkspace"
          else
            echo "Building Project (SPM)..."
            BUILD_ARG="-project App.xcodeproj"
          fi

          # [FIXED] Force Manual Signing and pass the Team ID explicitly
          xcodebuild archive \
            $BUILD_ARG \
            -scheme App \
            -configuration Release \
            -archivePath App.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE="Manual"
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportOptionsPlist ../../export_options.plist \
            -exportPath .
          
          mv App.ipa app_signed.ipa

    artifacts:
      - ios/App/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true