workflows:
  ios-workflow:
    name: iOS Build
    
    integrations:
      app_store_connect: Personal

    environment:
      xcode: latest
      node: latest
      cocoapods: default
      
      # AUTOMATIC SIGNING CONFIGURATION
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tracker.Inflight  # <--- REPLACE THIS WITH YOUR ACTUAL BUNDLE ID
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
          
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # Clean restart of ios folder
          rm -rf ios
          npx cap add ios
          npx cap sync
          
          # Check for Podfile to decide on Pods vs SPM
          cd ios/App
          if [ -f "Podfile" ]; then
            echo "Podfile found. Installing Pods..."
            pod install
          else
            echo "No Podfile found. Skipping CocoaPods (using SPM)."
          fi

      - name: iOS Code Signing
        script: |
          cd ios/App
          # Initialize the keychain with the profiles fetched in the 'environment' step
          xcode-project use-profiles

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # Use Codemagic's build-ipa utility.
          xcode-project build-ipa \
            --scheme "App" \
            --configuration "Release"

    artifacts:
      - "build/ios/ipa/*.ipa"
      - "/tmp/xcodebuild_logs/*.log"
      - "*.ipa"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true