workflows:
  ios-workflow:
    name: iOS Build
    
    integrations:
      app_store_connect: Personal

    environment:
      xcode: latest
      node: latest
      cocoapods: default
      
      # AUTOMATIC SIGNING CONFIGURATION
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tracker.Inflight  # Ensure this matches your actual ID
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
          
    scripts:
      - name: Install Dependencies
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      
      - name: Initialize iOS Platform
        script: |
          # Clean restart of ios folder
          rm -rf ios
          npx cap add ios
          npx cap sync
          
          # Check for Podfile to decide on Pods vs SPM
          cd ios/App
          if [ -f "Podfile" ]; then
            echo "Podfile found. Installing Pods..."
            pod install
          else
            echo "No Podfile found. Skipping CocoaPods (using SPM)."
          fi

      - name: Increment Build Number
        script: |
          # Automatically syncs Xcode build number with Codemagic Build ID
          # preventing "Duplicate Version" errors in TestFlight.
          cd ios/App
          echo "Updating build version to $BUILD_NUMBER"
          agvtool new-version -all $BUILD_NUMBER

      - name: iOS Code Signing
        script: |
          cd ios/App
          # Initialize the keychain with the profiles fetched in the 'environment' step
          xcode-project use-profiles

      - name: Build IPA (Signed)
        script: |
          cd ios/App
          
          # Check if a Workspace exists (created by CocoaPods) or just a Project
          if [ -d "App.xcworkspace" ]; then
            echo "Detailed Build: Detected App.xcworkspace. Building Workspace."
            
            xcode-project build-ipa \
              --workspace "App.xcworkspace" \
              --scheme "App" \
              --config "Release"
              
          else
            echo "Detailed Build: No Workspace found. Building App.xcodeproj."
            
            xcode-project build-ipa \
              --project "App.xcodeproj" \
              --scheme "App" \
              --config "Release"
          fi

    artifacts:
      - "ios/App/build/ios/ipa/*.ipa" # <--- FIXED: Locates the file correctly
      - "build/ios/ipa/*.ipa"
      - "*.ipa"
      - "/tmp/xcodebuild_logs/*.log"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true